name = "discord-choseisan"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Note: Static files are served via Cloudflare Pages
# See pages/ directory for landing pages

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# KV Namespaces removed - migration to D1 complete

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "discord-choseisan-db"
database_id = "f9c793aa-2850-4646-8d5d-271550fdc3ac"
migrations_dir = "migrations"
migrations_table = "d1_migrations"

# All variables are now only D1 database - no more switching needed