name = "discord-choseisan"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Note: Static files are served via Cloudflare Pages
# See pages/ directory for landing pages

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# KV Namespaces for production environment
[[env.production.kv_namespaces]]
binding = "SCHEDULES"
id = "6db94c56f3294de695e539020aec6700"

[[env.production.kv_namespaces]]
binding = "RESPONSES" 
id = "3399118d0fc24437ac694cb6c25e7dc8"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "SCHEDULES"
id = "6db94c56f3294de695e539020aec6700"
preview_id = "7278ac2a361a40b891f7e5f17b655594"

[[kv_namespaces]]
binding = "RESPONSES"
id = "3399118d0fc24437ac694cb6c25e7dc8"
preview_id = "a59f3cc9de6a4f0dbc463211ddbbaf6a"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "discord-choseisan-db"
database_id = "f9c793aa-2850-4646-8d5d-271550fdc3ac"

# Database type configuration
[vars]
DATABASE_TYPE = "d1"  # Switch to D1 database