name = "discord-choseisan"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "SCHEDULES"
id = "6a83c721d5aa47da900e1adda3f465e8"
preview_id = "schedules_kv_preview"

[[kv_namespaces]]
binding = "RESPONSES"
id = "14eebb7e00bb4cefaa04cd38e47eb324"
preview_id = "responses_kv_preview"

# D1 Database (alternative to KV)
# [[d1_databases]]
# binding = "DB"
# database_name = "discord-choseisan"
# database_id = "your-database-id"