/**
 * Constants - Legacy compatibility exports
 * 新しいコードでは src/constants/ApplicationConstants.ts を使用してください
 */

import { 
  TIME_CONSTANTS as NEW_TIME_CONSTANTS,
  DISCORD_CONSTANTS,
  ERROR_MESSAGES as NEW_ERROR_MESSAGES,
  NOTIFICATION_CONSTANTS
} from './ApplicationConstants';

/**
 * Discord API制限とUI制限 - レガシー互換性
 */
export const DISCORD_LIMITS = {
  MAX_EMBED_FIELDS: DISCORD_CONSTANTS.MAX_EMBED_FIELDS,
  MAX_COMPONENTS_PER_MESSAGE: DISCORD_CONSTANTS.MAX_ACTION_ROWS,
  MAX_SELECT_MENU_OPTIONS: 25,
  MAX_BUTTON_ROWS: DISCORD_CONSTANTS.MAX_ACTION_ROWS,
  MAX_BUTTONS_PER_ROW: DISCORD_CONSTANTS.MAX_COMPONENTS_PER_ROW,
  MAX_CONTENT_LENGTH: DISCORD_CONSTANTS.MAX_MESSAGE_CONTENT_LENGTH,
  MAX_EMBED_DESCRIPTION_LENGTH: DISCORD_CONSTANTS.MAX_EMBED_DESCRIPTION_LENGTH,
  MAX_EMBED_FIELD_VALUE_LENGTH: DISCORD_CONSTANTS.MAX_EMBED_FIELD_VALUE_LENGTH
} as const;

/**
 * 時間関連の定数 - レガシー互換性
 */
export const TIME_CONSTANTS = {
  SIX_MONTHS_SECONDS: NEW_TIME_CONSTANTS.SIX_MONTHS_SECONDS,
  MILLISECONDS_PER_SECOND: NEW_TIME_CONSTANTS.MILLISECONDS_PER_SECOND,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_MONTH: 30,
  SECONDS_PER_MINUTE: NEW_TIME_CONSTANTS.SECONDS_PER_MINUTE,
  SECONDS_PER_HOUR: NEW_TIME_CONSTANTS.SECONDS_PER_HOUR,
  SECONDS_PER_DAY: NEW_TIME_CONSTANTS.SECONDS_PER_DAY
} as const;

/**
 * Discordのメッセージフラグ
 */
export const DISCORD_FLAGS = {
  EPHEMERAL: 64,
  SUPPRESS_EMBEDS: 1 << 2,
  SUPPRESS_NOTIFICATIONS: 1 << 12
} as const;

/**
 * レート制限とバッチ処理
 */
export const RATE_LIMITS = {
  DEFAULT_BATCH_SIZE: 20,
  DEFAULT_BATCH_DELAY: 100,
  WEBHOOK_REQUESTS_PER_MINUTE: 30,
  CLOSURE_BATCH_SIZE: 15,
  CLOSURE_BATCH_DELAY: 100
} as const;

/**
 * KV操作関連
 */
export const KV_LIMITS = {
  FREE_TIER_WRITES_PER_DAY: 1000,
  FREE_TIER_READS_PER_DAY: 100000,
  PAID_TIER_STORAGE_GB: 1
} as const;

/**
 * 通知関連 - レガシー互換性
 */
export const NOTIFICATION_SETTINGS = {
  PR_MESSAGE_DELAY_MS: NOTIFICATION_CONSTANTS.PR_MESSAGE_DELAY_MS,
  CACHE_DURATION_MS: 5 * 60 * 1000, // 5分
  REMINDER_THRESHOLD_HOURS: 8
} as const;

/**
 * デフォルトリマインダータイミング - レガシー互換性
 */
export const DEFAULT_REMINDER_TIMINGS = [
  { type: '3d', hours: 72, message: '締切まで3日' },
  { type: '1d', hours: 24, message: '締切まで1日' },
  { type: '8h', hours: 8, message: '締切まで8時間' }
] as const;

/**
 * エラーメッセージ - レガシー互換性
 */
export const ERROR_MESSAGES = {
  SCHEDULE_NOT_FOUND: NEW_ERROR_MESSAGES.SCHEDULE_NOT_FOUND,
  INVALID_INPUT: '入力内容に問題があります。',
  INTERNAL_ERROR: '処理中にエラーが発生しました。',
  PERMISSION_DENIED: '権限がありません。',
  SCHEDULE_CLOSED: NEW_ERROR_MESSAGES.SCHEDULE_ALREADY_CLOSED,
  UNKNOWN_BUTTON: '不明なボタンです。',
  UNKNOWN_MODAL: '不明なモーダルです。',
  UNKNOWN_COMMAND: '不明なコマンドです。'
} as const;

/**
 * 成功メッセージ - レガシー互換性
 */
export const SUCCESS_MESSAGES = {
  SCHEDULE_CREATED: '日程調整を作成しました！',
  SCHEDULE_UPDATED: '日程調整を更新しました！',
  SCHEDULE_DELETED: '日程調整を削除しました。',
  RESPONSE_SAVED: '回答を保存しました！',
  REMINDER_SENT: 'リマインダーを送信しました。'
} as const;

/**
 * 色コード - レガシー互換性
 */
export const COLORS = {
  PRIMARY: DISCORD_CONSTANTS.COLORS.PRIMARY,
  SUCCESS: 0x2ecc71,
  WARNING: DISCORD_CONSTANTS.COLORS.WARNING,
  ERROR: DISCORD_CONSTANTS.COLORS.ERROR,
  INFO: DISCORD_CONSTANTS.COLORS.INFO,
  REMINDER: 0xffcc00
} as const;