name: Deadline Reminder

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-deadlines:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Check deadlines and send reminders
      env:
        WORKER_URL: ${{ secrets.WORKER_URL }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
      run: |
        curl -X POST "$WORKER_URL/cron/deadline-check" \
          -H "X-Cron-Secret: $CRON_SECRET" \
          -H "Content-Type: application/json" \
          -d '{"action": "check_deadlines"}'