name: Deadline Reminder

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  trigger-deadline-check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    - name: Trigger Worker
      run: |
        response=$(curl -s -w "\n%{http_code}" -X POST "${{ secrets.WORKER_URL }}/cron/deadline-check" \
          -H "X-Cron-Secret: ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json" \
          -d '{"action": "check_deadlines"}')
        
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | sed '$d')
        
        if [ "$http_code" -ne 200 ]; then
          echo "Request failed with status code: $http_code"
          echo "Response: $body"
          exit 1
        fi
        
        echo "Deadline check completed successfully"